checks:
  php:
    code_rating: true
    duplication: true

build:
  environment:
    php: "7.2"

  tests:
    before:
      - "phpunit"

before_commands:
  - "composer install --no-interaction --prefer-source"

filter:
  excluded_paths:
    - tests/
